<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="forms" tagdir="/WEB-INF/tags/forms" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>

<%@ page import="novemberdobby.teamcity.artifactLinkGen.Constants" %>

<c:set var="manage_url" value="<%=Constants.MANAGE_URL%>"/>
<c:set var="get_url" value="<%=Constants.GET_URL%>"/>

<style type="text/css">
table#links_table thead tr th, table#links_table tbody tr td {
  text-align: left;
  border: 1px solid #ccc;
}
</style>

<script type="text/javascript">
  BS.PortableArtifactLinker = {
    delete: function(guid) {
        BS.ajaxRequest(window['base_uri'] + '${manage_url}', {
            method: "POST",
            parameters: {
                'guid': guid,
            },
            onComplete: function(transport) {
                if(transport.status == 200)
                {
                    location.reload();
                }
                else
                {
                    alert("Failed to delete, code " + transport.status);
                }
            }
        });
      }
  };
</script>

<table id="links_table" cellpadding="6">
  <thead>
    <tr>
      <th>ID</th>
      <th>Generated by</th>
      <th>Build</th>
      <th>Artifact</th>
      <th>Expiry</th>
      <th>Remove link</th>
    </tr>
  </thead>
  <tbody>
    <c:forEach items="${links.entrySet()}" var="linkItem">
      <c:set var="guid" value="${linkItem.getKey()}"/>
      <c:set var="link" value="${linkItem.getValue()}"/>

      <c:set var="user" value="${usermodel.findUserById(link.getGeneratedByUserID())}"/>
      <c:set var="userId" value="<User ${link.getGeneratedByUserID()}>"/>
      
      <tr>
        <td>
        ${guid}
        </td>
        <td>
        ${fn:escapeXml(user == null ? userId : user.getUsername())}
        </td>
        <td>
        <a href="/viewLog.html?buildId=${link.getBuildID()}">${link.getBuildID()}</a>
        </td>
        <td>
        <a href="${get_url}?guid=${guid}&fromAdminPage=1">${fn:escapeXml(link.getArtifactPath())}</a>
        </td>
        <td>
        ${link.getExpiry() == null ? fn:escapeXml("<never>") : link.getExpiry()}
        </td>
        <td>
        <forms:button id="delete_link_${guid}" onclick="BS.PortableArtifactLinker.delete('${guid}')" className="btn btn-mini">Remove</forms:button>
        </td>
      </tr>
    </c:forEach>
  </tbody>
</table>