package novemberdobby.teamcity.artifactLinkGen;

import java.time.Instant;
import java.util.Date;

import jetbrains.buildServer.users.SUser;

public class LinkData {
    private Date Generated;
    private Long GeneratedByUserID;
    
    private Date Expiry;

    private Long BuildID;
    private String ArtifactPath;

    public LinkData(SUser user, Long expiryMins, Long buildId, String artifactPath) {
        Generated = Date.from(Instant.now());
        GeneratedByUserID = user.getId();

        if(expiryMins > 0) {
            Expiry = Date.from(Generated.toInstant().plusSeconds(expiryMins * 60)); //hmm
        }

        BuildID = buildId;
        ArtifactPath = artifactPath;
    }

    public boolean hasExpired() {
        return Expiry != null && Expiry.before(Date.from(Instant.now()));
    }

    @Override
    public String toString() {
        return String.format("Generated by user %s at %s, expires after %s. %s: %s", GeneratedByUserID, Generated, Expiry == null ? "<never>" : Expiry, BuildID, ArtifactPath);
    }
    
    public Date getGenerated() {
        return Generated;
    }

    public Long getGeneratedByUserID() {
        return GeneratedByUserID;
    }
    
    public Date getExpiry() {
        return Expiry;
    }

    public Long getBuildID() {
        return BuildID;
    }
    public String getArtifactPath() {
        return ArtifactPath;
    }
}